version: '3'
services:
    cli:
        image: silintl/php8:8.1
        volumes:
            - ./:/data
        env_file:
            - ./local.env
        environment:
            COMPOSER_CACHE_DIR: /tmp
        working_dir: /data
        command: ["true"]

